/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

/**
 * External dependencies
 */
// eslint-disable-next-line import/no-extraneous-dependencies
const CopyWebpackPlugin = require( 'copy-webpack-plugin' );
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	output: {
		...defaultConfig.output,
		path: path.resolve( process.cwd(), 'build-scripts' ),
	},
	entry: {
		...defaultConfig.entry(),
		'admin/settings': path.resolve(
			process.cwd(),
			'src/admin/settings',
			'index.scss'
		),
		'admin/ai-request-logs': path.resolve(
			process.cwd(),
			'src/admin/ai-request-logs',
			'index.tsx'
		),
		'admin/dashboard': path.resolve(
			process.cwd(),
			'src/admin/dashboard',
			'index.scss'
		),
		'experiments/connector-approval': path.resolve(
			process.cwd(),
			'src/experiments/connector-approval',
			'index.tsx'
		),
		'experiments/content-classification': path.resolve(
			process.cwd(),
			'src/experiments/content-classification',
			'index.tsx'
		),
		'experiments/abilities-explorer': path.resolve(
			process.cwd(),
			'src/experiments/abilities-explorer',
			'index.js'
		),
		'experiments/content-resizing': path.resolve(
			process.cwd(),
			'src/experiments/content-resizing',
			'index.tsx'
		),
		'experiments/example-experiment': path.resolve(
			process.cwd(),
			'src/experiments/example-experiment',
			'index.tsx'
		),
		'experiments/excerpt-generation': path.resolve(
			process.cwd(),
			'src/experiments/excerpt-generation',
			'index.tsx'
		),
		'features/image-generation': path.resolve(
			process.cwd(),
			'src/features/image-generation',
			'index.ts'
		),
		'experiments/meta-description': path.resolve(
			process.cwd(),
			'src/experiments/meta-description',
			'index.tsx'
		),
		'experiments/personas': path.resolve(
			process.cwd(),
			'src/experiments/personas',
			'index.tsx'
		),
		'experiments/editorial-notes': path.resolve(
			process.cwd(),
			'src/experiments/editorial-notes',
			'index.tsx'
		),
		'experiments/editorial-updates': path.resolve(
			process.cwd(),
			'src/experiments/editorial-updates',
			'index.tsx'
		),
		'experiments/summarization': path.resolve(
			process.cwd(),
			'src/experiments/summarization',
			'index.tsx'
		),
		'experiments/title-generation': path.resolve(
			process.cwd(),
			'src/experiments/title-generation',
			'index.tsx'
		),
		'experiments/slug-generation': path.resolve(
			process.cwd(),
			'src/experiments/slug-generation',
			'index.tsx'
		),
		'experiments/type-ahead': path.resolve(
			process.cwd(),
			'src/experiments/type-ahead',
			'index.tsx'
		),
		'experiments/comment-moderation': path.resolve(
			process.cwd(),
			'src/experiments/comment-moderation',
			'index.tsx'
		),
		'experiments/suggest-reply': path.resolve(
			process.cwd(),
			'src/experiments/suggest-reply',
			'index.tsx'
		),
		'experiments/alt-text-generation': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'index.tsx'
		),
		'experiments/alt-text-generation-media': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'media.ts'
		),
		'experiments/alt-text-generation-media-editor': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'media-editor.tsx'
		),
		'experiments/alt-text-generation-bulk': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'bulk.ts'
		),
		'experiments/summarization-bulk': path.resolve(
			process.cwd(),
			'src/experiments/summarization',
			'bulk.ts'
		),
		'experiments/content-translation': path.resolve(
			process.cwd(),
			'src/experiments/content-translation',
			'index.tsx'
		),
	},

	plugins: [
		...defaultConfig.plugins,

		// Copy DataViews CSS into build/ so the plugin can enqueue it
		// on WP versions where wp-dataviews is not a registered style.
		new CopyWebpackPlugin( {
			patterns: [
				{
					from: path.resolve(
						__dirname,
						'node_modules/@wordpress/dataviews/build-style/style.css'
					),
					to: path.resolve( __dirname, 'build/admin/dataviews.css' ),
				},
			],
		} ),

		// Remove empty `.js` files generated by webpack from style-only entries.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
