/**
 * Type definitions for image generation.
 */

/**
 * Provider metadata from image generation API.
 */
export interface ProviderMetadata {
	id: string;
	name: string;
	type: string;
}

/**
 * Model metadata from image generation API.
 */
export interface ModelMetadata {
	id: string;
	name: string;
}

/**
 * Generated image data (image part of generation result).
 */
export interface GeneratedImage {
	data: string;
	provider_metadata: ProviderMetadata;
	model_metadata: ModelMetadata;
}

/**
 * Result from generateImage / input for uploadImage.
 */
export interface GeneratedImageData {
	image: GeneratedImage;
	prompt: string;
	prompts?: string[];
}

/**
 * Result from uploadImage (imported image in media library).
 */
export interface UploadedImage {
	id: number;
	url: string;
	title: string;
}

/**
 * Post context passed to prompt generation (title, type, optional content).
 */
export interface PostContext {
	title: string;
	type: string;
	content?: string;
	[ key: string ]: string | undefined;
}

/**
 * Object shape for formatContext (key-value record).
 */
export type ContextRecord = Record< string, string | undefined >;

/**
 * Props for the AILabel component.
 */
export interface AILabelProps {
	label: string;
}

/**
 * Input parameters for the ai/image-import ability.
 */
export interface ImageImportAbilityInput {
	data: string;
	filename?: string;
	title?: string;
	description?: string;
	alt_text?: string;
	mime_type?: string;
	ai_generated?: boolean;
	[ key: string ]: string | number | boolean | undefined;
}

/**
 * Input parameters for the ai/image-generation ability.
 */
export interface ImageGenerationAbilityInput {
	prompt: string;
	reference?: string;
	[ key: string ]: string | undefined;
}

/**
 * Input parameters for the ai/image-prompt-generation ability.
 */
export interface ImagePromptGenerationAbilityInput {
	content: string;
	context?: string;
	style?: string;
	[ key: string ]: string | undefined;
}

/**
 * Callback type for image generation progress messages.
 */
export type ImageProgressCallback = ( message: string ) => void;

/**
 * A single entry in the image generation history.
 */
export interface HistoryEntry {
	generatedData: GeneratedImageData;
	/** Data URI used as reference input; undefined for fresh text-prompt generations. */
	referenceSrc?: string;
	/** History index of the entry whose image was used as the reference. */
	referenceHistoryIndex?: number;
	/** True when this entry was generated by refining a previously generated image. */
	isRefinement: boolean;
}
